language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
   - php: hhvm
  fast_finish: true

install:
  - composer self-update
  - composer install

script:
 - vendor/bin/phpunit -v
