language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
 - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
 - if [ "${TRAVIS_PHP_VERSION:0:3}" == "5.5" ]; then PHPUNIT_VERSION=4.8; else PHPUNIT_VERSION=5.7; fi
 - wget -O phpunit.phar https://phar.phpunit.de/phpunit-${PHPUNIT_VERSION}.phar

install:
  - composer self-update
  - composer install

script:
 - php phpunit.phar -v
