language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_install:
 - if [ "${TRAVIS_PHP_VERSION:0:3}" == "5.5" ]; then PHPUNIT_VERSION=4.8; else PHPUNIT_VERSION=5.7; fi
 - wget -O phpunit.phar https://phar.phpunit.de/phpunit-${PHPUNIT_VERSION}.phar

install:
  - composer self-update
  - composer install

script:
 - vendor/bin/parallel-lint --exclude vendor .
 - php phpunit.phar -v

after_success:
 - travis_retry bash <(curl -s https://codecov.io/bash) -f build/clover/tests.xml
